main: com.gmail.alexradu04.manhunt.MainPlugin
name: ManhuntPlugin
version: ${version}
commands:
  hunt:
    description: Starts hunt season.
    usage: "Usage: '/hunt [player] to start the manhunt minigame on a player"
  stophunt:
    description: Stops the hunt season
    usage: /stophunt